### ISSUE TITLE
Trino - Allow login using BasicAuthentication

### ISSUE THREAD

**Issue by jkleinkauff** [erezsh/sqeleton#14]
I'm using reladiff, but the classes mentioned below come from sqeleton.

This is the official conn string for Trino:
`trino://<username>:<password>@<hostname>:8080/<database>`

But if you try to login using it like
```
table = connect_to_table(
    f"trino://{TRINO_USER}:{TRINO_PASS}@{TRINO_HOST}/catalog/schema",
    "trino_queries",
    ("query_id"),
)
```
It throws:
`TypeError: Connection.__init__() got an unexpected keyword argument 'password'`

For the Trino [connection](https://github.com/erezsh/sqeleton/blob/master/sqeleton/databases/trino.py#L39) I think we could do something similar the Presto connection is doing here https://github.com/erezsh/sqeleton/blob/master/sqeleton/databases/presto.py#L173

This will allow us to use a db_info like
```
db_conf_trino = {
    ...
    "user": TRINO_USER,
    "password": TRINO_PASS,
    "auth": "basic",
    "http_scheme": "https",
}


table = connect_to_table(
    db_conf_trino,
    "trino_queries",
    ("query_id"),
)
```

@erezsh I can help with a pr if you think this makes sense.

Python 3.12.3
reladiff v0.5.1

**Comment by erezsh** [comment]
You're right, currently trino doesn't accept a password.

If you'd like to submit a PR, that would be welcome!
