### ISSUE TITLE
Add trino UUID data type support

### ISSUE THREAD

**Issue by Ryuk-me** [erezsh/sqeleton#19]
While querying PostgreSQL using trino, getting this error

```
raise NotImplementedError(f"Cannot use a column of type {kt} as a key")
    NotImplementedError: Cannot use a column of type UnknownColType(text='uuid') as a key
```

: Primary Key of the postgres table is of data type `UUID`

![image](https://github.com/user-attachments/assets/80606011-9b82-4bbb-8f32-f9f90e0e7609)

**Comment by erezsh** [comment]
This issue was also discussed here: https://github.com/erezsh/reladiff/discussions/23

**Comment by erezsh** [comment]
@Ryuk-me I create a PR that is supposed to solved this. Can you give it a try and let me know if it works for you too?  https://github.com/erezsh/reladiff/pull/28

**Comment by Ryuk-me** [comment]
> @Ryuk-me I created a PR that is supposed to solved this. Can you give it a try and let me know if it works for you too?
> 
> [erezsh/reladiff#28](https://github.com/erezsh/reladiff/pull/28)

Solved Thank you !
